### ISSUE TITLE
Add Mathematical expression

### ISSUE THREAD

**Issue by Susmita-Dey** [atapas/markdown-cheatsheet#10]
**Is your feature request related to a problem? Please describe.**
I wanna add Mathematical expression to the README file as GitHub supports Maths in Markdown.

**Describe the solution you'd like**
Adding Math expression syntax to improve the cheatsheet

**Describe alternatives you've considered**
None

**Additional context**

**Code:**

```
When $a \ne 0$, there are two solutions to $(ax^2 + bx + c = 0)$ and they are 

$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$
```

**Output:**

When $a \ne 0$, there are two solutions to $(ax^2 + bx + c = 0)$ and they are 

$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$

**Comment by atapas** [comment]
Hey @Susmita-Dey I see some are added already: https://github.com/atapas/markdown-cheatsheet#mathematical-expressions

Do we want to add more?

**Comment by Susmita-Dey** [comment]
@atapas I just wanna add the above code.
