### ISSUE TITLE
Add Syntax for Code Block for Various Languages

### ISSUE THREAD

**Issue by Susmita-Dey** [atapas/markdown-cheatsheet#2]
**Is your feature request related to a problem? Please describe.**
Yes, the syntax for code block for different languages in the general form is missing.

**Describe the solution you'd like**
I want to add the syntax for the code block.

**Describe alternatives you've considered**
No.

**Additional context**
![image](https://user-images.githubusercontent.com/79099734/171643953-27040af2-6987-48ad-8a6a-2ed8bfec3fdb.png)

**Comment by atapas** [comment]
@Susmita-Dey do you want to take it up?
