### ISSUE TITLE
Add Diagrams Syntax

### ISSUE THREAD

**Issue by melvincwng** [atapas/markdown-cheatsheet#20]
**Is your feature request related to a problem? Please describe.**
I wish to add the syntax to generate diagrams in GitHub markdown. 

**Describe the solution you'd like**
I will raise a PR containing the syntax for generating diagrams in markdown files on GitHub.

**Additional context**
Submitting a PR as part of Hacktoberfest 2022 🎉

**Comment by melvincwng** [comment]
@atapas Hi Tapas, please kindly assign me this issue & label it with 'hacktoberfest', after which I would proceed to submit a PR with your kind permission :).

Thanks!

**Comment by atapas** [comment]
> @atapas Hi Tapas, please kindly assign me this issue & label it with 'hacktoberfest', after which I would proceed to submit a PR with your kind permission :).
> 
> 
> 
> Thanks!

Done!
