### ISSUE TITLE
Comments in Markdown

### ISSUE THREAD

**Issue by coder-oj** [atapas/markdown-cheatsheet#28]
**Is your feature request related to a problem? Please describe.**
I noticed that the information about how to add a comment in a markdown file is missing here. Can I take this up under hacktober fest?

**Comment by atapas** [comment]
> **Is your feature request related to a problem? Please describe.** I noticed that the information about how to add a comment in a markdown file is missing here. Can I take this up under hacktober fest?

Yes please... If it is missing.
