### ISSUE TITLE
Add highlight syntax

### ISSUE THREAD

**Issue by AhnafAhamed** [atapas/markdown-cheatsheet#38]
**Is your feature request related to a problem? Please describe.**
The highlight syntax is missing

**Describe the solution you'd like**
Add documentation for highlight syntax

**Comment by AhnafAhamed** [comment]
@atapas I would like to work on this issue. Thanks

**Comment by aashishxetri5** [comment]
Hi @AhnafAhamed, There's already an issue created for this #25 and a PR has also been submitted for this #26. Please find another issue to work on.

**Comment by AhnafAhamed** [comment]
Thanks for the heads up @aashishxetri5
